server:
  shutdown: immediate

spring:
  application:
    name: springboot-with-testcontainer
    temporal:
      type: LOCAL
      host: localhost:7233
logging:
  level:
    org.springframework.data: DEBUG

